# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sanjay Rajjan
title: Junior @ Prosper High School
#email: brett.h@email.co.uk
website: sanjay.rajjan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  sanjay-rajjan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sanjayrajjan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: UG-54FW7H77PD
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I’m Sanjay Rajjan, a student at Prosper High School. I started learning computer programming in middle school through the Make.Hack.Build program at [Do Space](https://dospace.org). I’m also a member of the varsity tennis team at PHS. I enjoy playing and coaching chess in my free time. 
  
  I founded the Chess Club at Prosper High School and established a non-profit organization called  [Chess Together](https://chess-together.org) to teach chess to kids and special children. I’ve coached over 30 kids through the PHS Chess Club and Chess Together Non-Profit organization.

  I am available for a summer internship from June to July 2024.
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Prosper High School
        caption: 2021 - 2025
        description: | # this will include new lines to allow paragraphs
          My interests are centered on computer science in High school. I took *AP Computer Science Principles* and am currently doing *AP Computer Science A* to further improve my skills and knowledge in this area. 
          
          I also have a deep passion for artificial intelligence and data science due to the emergence of AI and its potential to be an integral part of our society, especially in the future. 
          
          I also have taken *AP Statistics* in high school as one of my classes because it is particularly very useful for data science.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chess Together
        link: chess-together.org
        # link_text: boringcompany.com
        sub_title: Founder
        caption: December 2022 - Present
        description: | # this will include new lines to allow paragraphs
            Established non-profit organization Chess Together to teach chess to kids and children with special needs. 
            By teaching chess and organizing tournaments, we create a supportive environment where kids can learn, compete, and build valuable life skills.    

  - title: Awards and Recognitions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tennis
        caption: 2021 - Present
        # sub_title: BSc Computer Science
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * Won 3 x Gold in Mixed Doubles
          * Won 1 x Bronze in Boys Doubles
          * Won 1 x Silver in Boys Singles

      - layout: left
        title: Chess
        caption: 2015 - Present
        # sub_title: BSc Computer Science
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * 2 x Nebraska State Champion - 1st Place
          * 1 x Nebraska State Champion - 2nd Place
          * 2015 US Open Junior Champion - 1st Place
          * National Elementary Champion - 3rd Place

  - title: Volunteering
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stephen Center Homeless Shelter
        caption: Jan 2017 - Nov 2019
        sub_title: Omaha, NE
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
           Helped in Meal preparation and Serving to People in Homeless Shelter.

      - layout: left
        title: Aubrey Public Library
        caption: Jan 2023 - Aug 2023
        sub_title: Aubrey, TX
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
           Shelving and Sorting books and magazines. Organizing materials on shelves. Keeping shelves neat. Assisting patrons with borrowing books. Bringing requested books to members. Keeping the library clean and tidy. Ensuring order in activity areas.

      - layout: left
        title: Little Elm Public Library
        caption: Feb 2023 - Aug 2023
        sub_title: Little Elm, TX
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
           Shelving and Sorting books and magazines. Organizing materials on shelves. Keeping shelves neat. Assisting patrons with borrowing books. Bringing requested books to members. Keeping the library clean and tidy. Ensuring order in activity areas.
          
  - title: News and Articles
    layout: text
    content: | # this will include new lines to allow paragraphs
      * [Chess Together Non-Profit Organization Launched](https://chess-together.org/_posts/2024-02-12-chess-together-non-profit/)
      * [Chess club conducts 1st meetings, plans to participate in tournaments against Rock Hill](https://eaglenationonline.com/31811/news/chess-club-conducts-first-meetings-hopes-to-participate-in-tournaments-against-rockhill/)
      * [Out of Staters Sweep US Junior and US Senior Opens](https://www.il-chess.org/news/804-2015-us-junior-us-senior-results)
      

      

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References available on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
